<?php

/**
*
 */
class Scripts extends Megad
{
    private $object;

    function __construct()
    {
        $this->object =  new Objects();
    }


    function playSound($sound)
    {
        parent::playSound($sound); // TODO: Change the autogenerated stub
    }




    function set($num, $val, $id_device=null)
    {
        parent::set($num, $val, $id_device); // TODO: Change the autogenerated stub
    }




    /** Ищем и выполняем скрипты, которые сответсвуют объектам и их методам,
     подходящим по текущему периоду времени */

    function cron(int $time)
    {
        $this->scheduler('',$time,'c');
    }




    /**
     * Ищем и выполняем скрипты или методы обекта методам из таблицы расписаний
     *
     * @param string $day - день недели, месяца или дата выполнния скрипта
     * @param string $time - время выполнения скрипта
     * @param string $type - тип, по которому отбираем данные d - ежедневные, w - еженедельные, m - ежемесячные, c - ежеминутные
     * @return void
     */

    function scheduler($day, $time, $type)
    {


        $sql = parent::$db->query("SELECT  scheduler_tasks.id AS id_task, scheduler_tasks.method AS method, scheduler_tasks.script AS script 
                                    FROM scheduler_tasks        
                                    INNER JOIN scheduler_points ON scheduler_tasks.id =  scheduler_points.id_task
                                    WHERE scheduler_points.days LIKE '%$day%' AND scheduler_points.time = '$time'
                                    AND `scheduler_points`.`type` = '$type' ");


        while ($action = $sql->fetch(PDO::FETCH_OBJ))
        {
            //Выполняем действие для метода, если он указан. Если не указан, то для скрипта
            if($action->method != null)
            Action::runAction($action->method, 'scheduler', $action->id_task );
            else
                $this->runscript($action->script);

        }

    }





    /**
     * Выполняем нужный скрипт
     *
     * @param int $id_object
     * @param int $object ид объекта, который передается
     */
    function runscript($idScript, $param = null)
    {
        if($idScript) {
            $scriptsql = parent::$db->query("SELECT scripts.link AS link FROM scripts 
                                         WHERE scripts.id = $idScript");

            $script = $scriptsql->fetch(PDO::FETCH_OBJ);


            $dir = str_replace(' ', '\ ', __DIR__);
            exec("cd " . $dir . "/../scripts && php -f {$script->link} {$param} &"); //выполняем внешний скрипт

            System::addLog('system', 'Script "' . $script->link . ' ' . $param . '" is running');

            return true;
        }else {
            System::addLog('error', 'Вызван метод, у которого не указан скрипт');
            return false;
        }
        
    }


}