<?php

/**
*
 */
class Scripts extends Megad
{
    private $object;

    function __construct()
    {
        $this->object =  new Objects();
    }


    function play_sound($sound)
    {
        parent::play_sound($sound); // TODO: Change the autogenerated stub
    }




    function set($num, $val, $id_device=null)
    {
        parent::set($num, $val, $id_device); // TODO: Change the autogenerated stub
    }




    /** Ищем и выполняем скрипты, которые сответсвуют объектам и их методам,
     подходящим по текущему периоду времени */

    function cron(int $time)
    {
        $this->scheduler('',$time,'c');
    }




    /**
     * Ищем и выполняем скрипты, которые соответсвуют объектам и их методам из таблицы расписаний
     *
     * @param string $day - день недели, месяца или дата выполнния скрипта
     * @param string $time - время выполнения скрипта
     * @param string $type - тип, по которому отбираем данные
     * @return void
     */

    function scheduler($day, $time, $type)
    {


        $sql = parent::$db->query("SELECT  scheduler_tasks.method AS method FROM scheduler_tasks
                                    INNER JOIN scheduler_points ON scheduler_tasks.id =  scheduler_points.id_task
                                    WHERE scheduler_points.days LIKE '%$day%' AND scheduler_points.time = '$time'
                                    AND `scheduler_points`.`type` = '$type' ");


        while ($action = $sql->fetch(PDO::FETCH_OBJ))
        {
            //Выполняем действие для метода
            Action::runAction($action->method);
        }

    }





    /**
     * Выполняем нужный скрипт
     *
     * @param int $id_object
     */
    function runscript($idScript, $method = null)
    {

        $scriptsql = parent::$db->query("SELECT scripts.link AS link FROM scripts 
                                         WHERE scripts.id = $idScript");

        $script = $scriptsql->fetch(PDO::FETCH_OBJ);


           $dir = str_replace(' ', '\ ', __DIR__);
           system("cd " . $dir . "/../scripts && php -f {$script->link} {$method} &"); //выполняем внешний скрипт

           System::addlog('Script "' . $script->link . ' ' . $method . '" is running');

           return true;


    }









}