<?php

/**
*
 */
class Scripts extends Megad
{
    private $object;

    function __construct()
    {
        $this->object =  new Objects();
    }


    function play_sound($sound)
    {
        parent::play_sound($sound); // TODO: Change the autogenerated stub
    }




    function set($num, $val, $id_device=null)
    {
        parent::set($num, $val, $id_device); // TODO: Change the autogenerated stub
    }




    /** Ищем и выполняем скрипты, которые сответсвуют объектам и их методам, содержащимся в таблице cron
     и подходящим по текущему периоду времени */

    function cron(int $time)
    {

        $sql = parent::$db->query("SELECT scripts.link, methods.id_object, cron.method FROM cron 
                                    INNER JOIN methods ON cron.method = methods.id 
                                    INNER JOIN scripts ON methods.script = scripts.id 
                                    WHERE cron.period=$time");

        while ($script = $sql->fetch(PDO::FETCH_OBJ))
        {
            system("cd custom_scripts && php -f {$script->link} &"); //выполняем внешний скрипт
            System::addlog('Script "'.$script->link.'" is running');
        }

    }






    /**
     * Ищем и выполняем скрипты, которые соответсвуют объектам и их методам из таблицы расписаний
     *
     * @param int $day - день недели, месяца или дата выполнния скрипта
     * @param string $time - время выполнения скрипта
     * @param string $type - тип, по которому отбираем данные
     * @return void
     */

    function scheduler(int $day, string $time, string $type)
    {

        $sql = parent::$db->query("SELECT scripts.link, methods.id_object, scheduler_tasks.method FROM scheduler_tasks 
                                    INNER JOIN methods ON scheduler_tasks.method = methods.id 
                                    INNER JOIN scripts ON methods.script = scripts.id
                                    INNER JOIN scheduler_points ON scheduler_tasks.id =  scheduler_points.id_task
                                    WHERE scheduler_points.days LIKE '%$day%' AND scheduler_points.time = '$time' AND `scheduler_points`.`type` = '$type' ");

        while ($script = $sql->fetch(PDO::FETCH_OBJ))
        {
            system("cd custom_scripts && php -f {$script->link} &"); //выполняем внешний скрипт
            System::addlog('Script "'.$script->link.'" is running');
        }

    }





    /**
     * Выполняем нужный скрипт для выбранного объекта
     *
     * @param int $id_object
     */
    function runscript($id_object, $id_method, $method=null)
    {

       $script = $this->object->get($id_object, $id_method, $method); //Получаем ссылку на скрипт

       //Если у объекта есть скрипт
       if ($script!=null) {

           $dir = str_replace(' ', '\ ', __DIR__);
           system("cd " . $dir . "/../scripts/custom_scripts && php -f {$script->link} {$method} &"); //выполняем внешний скрипт

           System::addlog('Script "' . $script->link . ' ' . $method . '" is running');
       }else{
           //Если скрипта нет
           return false;
       }

    }









}